const loginFields = [
	{
		labelText: "Email address",
		labelFor: "email-address",
		id: "email-address",
		name: "email",
		type: "email",
		autoComplete: "email",
		isRequired: true,
		placeholder: "Email address",
	},
	{
		labelText: "Password",
		labelFor: "password",
		id: "password",
		name: "password",
		type: "password",
		autoComplete: "current-password",
		isRequired: true,
		placeholder: "Password",
	},
];

const signupFields = [
	{
		labelText: "FirstName",
		labelFor: "FirstName",
		id: "FirstName",
		name: "FirstName",
		type: "text",
		autoComplete: "FirstName",
		isRequired: true,
		placeholder: "Osa",
	},
	{
		labelText: "LastName",
		labelFor: "LastName",
		id: "LastName",
		name: "LastName",
		type: "text",
		autoComplete: "LastName",
		isRequired: true,
		placeholder: "Ikhinmwin",
	},
	{
		labelText: "Email address",
		labelFor: "email-address",
		id: "email-address",
		name: "email",
		type: "email",
		autoComplete: "email",
		isRequired: true,
		placeholder: "osa@419.com",
	},
	{
		labelText: "Password",
		labelFor: "password",
		id: "password",
		name: "password",
		type: "password",
		autoComplete: "current-password",
		isRequired: true,
		placeholder: "Password",
	},
	{
		labelText: "Confirm Password",
		labelFor: "confirm-password",
		id: "confirm-password",
		name: "confirm-password",
		type: "password",
		autoComplete: "confirm-password",
		isRequired: true,
		placeholder: "Confirm Password",
	},
];

export { loginFields, signupFields };
